name: Deploy Lambda Function

on:
    workflow_dispatch:
    
jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python3 -m pip install toml utils
          python3 -m pip install --upgrade pip \
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python3 -m pytest test/ # Run tests located in the /test directory

  Dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function 
        run: zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
            aws lambda update-function-code \
            --function-name ${{ secrets.AWS_ARN_LAMBDA_DEV }} \
            --zip-file=fileb://code.zip

  Prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    needs: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        id: prod
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
              Changes in this Release
              - First Change
              - Second Change
          draft: false
          prerelease: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function 
        run: zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name ${{ secrets.AWS_ARN_LAMBDA_PROD }} \
          --zip-file=fileb://code.zip