name: Deploy Lambda Function

on:
    push:
        branches: [dev, main]
    
    pull_request:
        branches: [dev, main]

    workflow_dispatch:
    
jobs:
  
    dev:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                aws-region: us-east-1

            - name: Install zip tool
              uses: montudor/action-zip@v1

            - name: Create Zip file for Lambda Function 
              run: zip -r code.zip .
  
            - name: Deploy to AWS Lambda
              run: | 
                  aws lambda update-function-code \
                  --function-name ${{ secrets.AWS_ARN_LAMBDA_DEV }} \
                  --zip-file=fileb://code.zip

    prod:
        runs-on: ubuntu-latest
        environment: prod
        needs: dev
        steps:
            - name: Checkout
              uses: actions/checkout@v2
      
            - name: Create Release
              id: prod
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                tag_name: ${{ github.ref_name }}
                release_name: Release ${{ github.ref_name }}
                body: |
                    Changes in this Release
                    - First Change
                    - Second Change
                draft: false
                prerelease: false

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                aws-region: us-east-1

            - name: Install zip tool
              uses: montudor/action-zip@v1

            - name: Create Zip file for Lambda Function
              run: cd src && zip -r code.zip .
            
            - name: Create Zip file for Lambda Function Test
              run: cd test && zip -r test.zip .
  
            - name: Deploy to AWS Lambda
              run: | 
                  aws lambda update-function-code \
                  --function-name ${{ secrets.AWS_ARN_LAMBDA_DEV }} \
                  --zip-file=fileb://test/test.zip

            - name: Deploy to AWS Lambda
              run: | 
                aws lambda update-function-code \
                --function-name ${{ secrets.AWS_ARN_LAMBDA_PROD }} \
                --zip-file=fileb://src/code.zip